name: pcrglobwb_utils

channels:
  - conda-forge

dependencies:
  - python>=3.6
  - rasterio>=1.0.21
  - xarray>=0.15.0
  - pandas>=0.25.1
  - numpy>=1.16.5
  - matplotlib>=3.2.0
  - ipython
  - notebook
  - click
  - scipy
  - pip:
    - spotpy>=1.5.8
    - netCDF4
