name: pcrglobwb_utils

channels:
  - conda-forge

dependencies:
  - python>=3.7
  - rasterio>=1.1
  - xarray>=0.18
  - pandas>=1.2
  - numpy>=1.20
  - matplotlib>=3.2.0
  - geopandas>=0.9
  - rioxarray>=0.4
  - ipython
  - nbconvert
  - notebook
  - click>=7.1.1
  - scipy
  - xlrd>=2.0
  - openpyxl>=3.0.7
  - descartes
  - spotpy>=1.5.8
  - netcdf4
  - setuptools>=49.6
  - pyyaml
  - pcraster